dt_web_home:
    path:      /
    defaults:  { _controller: DtWebBundle:HomePage:index }
    
dt_web_point_of_interest:
    path:      /bezienswaardigheden
    defaults:  { _controller: DtWebBundle:Poi:index }
    
dt_web_point_of_interests_pagination:
    path:       /bezienswaardigheden/{start}/{limit}
    defaults:  { _controller: DtWebBundle:Poi:Pois }
    options:
        expose: true
        
dt_web_point_of_interests_countries:
    path:       /bezienswaardigheden/landen
    defaults:  { _controller: DtWebBundle:Poi:countries }
    options:
        expose: true
        
dt_web_point_of_interests_tags:
    path:       /bezienswaardigheden/tags
    defaults:  { _controller: DtWebBundle:Poi:tags }
    options:
        expose: true
    
dt_web_travel_planner:
    path:      /reisplanner
    defaults:  { _controller: DtWebBundle:TravelPlanner:index }
    
dt_web_travel_neotest:
    path:      /neo4jtest
    defaults:  { _controller: DtWebBundle:TravelPlanner:neotest }
    
dt_web_contact:
    path:      /contact
    defaults:  { _controller: DtWebBundle:Contact:index }
    
    


#api -------------------------------
dt_api_locations:
    path:       /api/locations
    defaults:   { _controller: DtWebBundle:Api:locations }
    options:
        expose: true
        

dt_api_countries:
    path:       /api/countries
    defaults:   { _controller: DtWebBundle:Api:countries }
    options:
        expose: true
        
dt_api_route:
    path:       /api/route/{startLocation}-{endLocation}
    defaults:   { _controller: DtWebBundle:Api:route }
    options:
        expose: true
        
dt_api_pois_by_region:
    path:       /api/pois/region/{region}
    defaults:   { _controller: DtWebBundle:Api:getPoisByRegion }
    options:
        expose: true
        
dt_api_pois:
    path:       /api/pois/all/{offset}-{limit}
    defaults:   { _controller: DtWebBundle:Api:getAllPois, limit: 10, offset: 0 }
    options:
        expose: true